### ISSUE TITLE
No graph shown

### ISSUE THREAD

**Issue by BigDoom** [bobzer/weather-card#7]
Probably something simple I'm overlooking here, but can't seem to find what. I really like the look of this card with the graph, but for some reason it shows no graph in my setup. See below.

![image](https://user-images.githubusercontent.com/1062020/75114980-f246e800-565a-11ea-909f-4e9fb5aef8cd.png)

What am I doing wrong?

**Comment by thehawkes** [comment]
set `graph: true` and it should work
that option is not documented

```
current: true
details: true
forecast: true
graph: true
```

**Comment by BigDoom** [comment]
Perfect, that did the trick. Thanks!
